name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install uv
      run: pip install uv
      
    - name: Create venv and install dependencies
      working-directory: ./backend
      run: |
        uv venv
        . .venv/bin/activate
        uv pip install -r requirements.txt
        
    - name: Run tests
      working-directory: ./backend
      run: |
        . .venv/bin/activate
        python -m pytest tests/